### ISSUE TITLE
solucion-labs

### ISSUE THREAD

**Issue by Jerimy2021** [cs1000-utec/labs#10]
Deseo agregar los pasos de solución del laboratorio número 12.
Motivo: Un punto extra en la PC1.

**Comment by franciscovilchezv** [comment]
Proceder con los cambios, aunque aún no tengo bien claro los pasos que se agregarán, pero ya le comento cualquier observación en el PR

**Comment by franciscovilchezv** [comment]
Ahora que lo pienso, este cambio será agregado en el repositorio `solucion-labs` ?   De ser así, debe de crear este issue en dicho repositorio.  Detallar un poco más a que se refiere por agregar los pasos.  De refiere al archivo solución .pyibn ?

**Comment by Jerimy2021** [comment]
Ok.

**Comment by Jerimy2021** [comment]
No encuentro el repositorio solución-labs, me podría indicar, por favor.
