### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by andreaUTEC** [cs1000-utec/labs#11]
Buenos días profesor he notado errores en el Lab 7, en las siguientes palabras:
1-agregar numeros a la url
Observación: A "números" le hace falta la tilde.
2-agregar los numeros como parametros de la funcion
Observación: A "números", "parámetros" y "función" les hace falta la tilde.
![LAB 7](https://user-images.githubusercontent.com/91233193/145449023-d8773ea5-608b-4fe4-beb4-1e3dda876ccb.png)
Motivo: Un punto extra en la PC1.

**Comment by franciscovilchezv** [comment]
Proceder con el cambio
