### ISSUE TITLE
Error ortográfico 

### ISSUE THREAD

**Issue by Yoselyn214** [cs1000-utec/labs#12]
La palabra opción lleva tilde. Como verá en el esto de explicación para la PC2 .
En la parte que dice sobre los temas y en la otra parte que dice sobre la presentación. 
No se está poniendo opción con tilde como es correcto.

![Screenshot_20211209-114348_Samsung Internet](https://user-images.githubusercontent.com/91152700/145452440-5834737c-d395-4586-a66a-4900b5331932.jpg)
Motivo: Punto extra en PC1.

**Comment by franciscovilchezv** [comment]
Proceder con el cambio

**Comment by franciscovilchezv** [comment]
Este issue es de la PC2. Cerrado
