### ISSUE TITLE
Explicación del repaso.

### ISSUE THREAD

**Issue by Sandovl0593** [cs1000-utec/labs#13]
Buenoas tardes. En el laboratorio 7 - PC1 Office Hours:

![a](https://user-images.githubusercontent.com/90804102/145462362-ba2e3bbe-ac28-42aa-ab08-9d27f58a9d9e.png)

En la parte de "codificar lo que nos pide el problema" (que hace falta una mayúscula al inicio de la viñeta).

Los dos parámetros que son ``
num1
`` y ``
num2
`` se debería resolver las operaciones en un solo operando, excepto en la ``
suma. Así sería más coherente y entendible la explicación.
``.

Motivo del detalle: Un punto extra en la PC1.
Muchas gracias.

**Comment by franciscovilchezv** [comment]
Proceder con los cambios

**Comment by Sandovl0593** [comment]
Buenas tardes, este es la parte modificada del error de la muestra en el Lab7:

# 
3. Codificar lo que nos pide el problema.
```python
suma = int(num1) + int(num2)
resta = int(num1) - int(num2)
mult = int(num1) * int(num2)
divi = int(num1) / int(num2)
```

El motivo de la modificación es de mejorar el entendimiento a detalle de los labs.

Muchas gracias.
