### ISSUE TITLE
Errores ortográficos - Lab 12

### ISSUE THREAD

**Issue by iranalvarez27** [cs1000-utec/labs#18]
Buenas tardes, profesor.

A continuación le envio las correcciones de algunos errores ortográficos que encontre en el repositorio del lab 12.

* Hay una redundancia de "cada una" en la siguiente oración:  _Se cuenta con un dataset (se descarga automáticamente en el modulo de magia negra) con 189 células distintas, *cada una* con 22mil características *cada una.*_
* Falta una tilde en la letra primera "o" de _modulo_
* Falta una tilde en la última "a" de _ayudaran_
![error](https://user-images.githubusercontent.com/91108632/145732449-4e35caf3-2e9b-43a6-82d0-6140e6f3fb12.png)

* Falta una tilde en la letra "u" de _ejecutelos_
![error3](https://user-images.githubusercontent.com/91108632/145731853-6fd07665-5b3b-444b-8430-ac925d7ab792.png)

* Falta una tilde en la letra "u" de _numero_
* Falta una tilde en la letra "i" de _linea_
![error4](https://user-images.githubusercontent.com/91108632/145731898-02b0d538-7765-41cc-b98f-4bb11261af53.png)

* Corrección de la palabra _en_ por **entre**
![error5](https://user-images.githubusercontent.com/91108632/145731935-37974496-3e70-4960-9d8f-dd563ee585d5.png)

* Falta una tilde en la letra "o" de _prediccion_
![error6](https://user-images.githubusercontent.com/91108632/145731984-368843fb-20cf-42bb-a5ec-fdbc0a2ca1e6.png)

Motivo: punto para la PC1

**Comment by franciscovilchezv** [comment]
Proceder, pero creo que "imagen" no lleva tilde. Verificar

**Comment by iranalvarez27** [comment]
Si, tiene razón "imagen" no lleva tílde. Lo confundí con "imágenes".
