### ISSUE TITLE
Errores ortográficos

### ISSUE THREAD

**Issue by andrewkc** [cs1000-utec/labs#20]
A continuación los errores ortográficos que he observado:

**Error ortográfico en el repositorio de Lab 11**
- Falta tilde a la palabra "camara" y "lineas" (cámara, líneas).

![errorlab11](https://user-images.githubusercontent.com/91230053/145909833-3dd624bf-2716-416f-8ab7-ab64dd6b7846.png)

**Error ortográfico en el repositorio de Lab 10**
- Falta una coma entre las palabras "búsqueda" y "pero".

![image](https://user-images.githubusercontent.com/91230053/145910195-56df3fdf-a205-472e-8c04-3ba4748769ec.png)

- Falta tilde en la palabra "traves" (través).

![image](https://user-images.githubusercontent.com/91230053/145910314-f5c1e0b4-016f-46d3-ae63-52b1eec9a9cd.png)

Motivo: 1 punto para la PC1

**Comment by franciscovilchezv** [comment]
Proceder
