### ISSUE TITLE
Explicación del repaso

### ISSUE THREAD

**Issue by Sandovl0593** [cs1000-utec/labs#21]
### Buenoas tardes. En el laboratorio 7 - PC1 Office Hours:

![a](https://user-images.githubusercontent.com/90804102/145462362-ba2e3bbe-ac28-42aa-ab08-9d27f58a9d9e.png)

En la parte de "codificar lo que nos pide el problema" (que hace falta una mayúscula al inicio de la viñeta).

Los dos parámetros que son ``
num1
`` y ``
num2
`` se debería resolver las operaciones en un solo operando, excepto en la ``
suma
``.  Así sería más coherente y entendible la explicación..

Motivo del detalle: Un punto extra en la PC1.

## PD: Tuve que repetirlo, porque he cerrado el issue sin querer. Gracias.

**Comment by franciscovilchezv** [comment]
Proceder.  Lo de las mayusculas ya fue arreglado por si acaso

**Comment by Sandovl0593** [comment]
### Prueba del commit:

![Captura de pantalla 2021-12-14 170830](https://user-images.githubusercontent.com/90804102/146087946-18a9c6fd-7b96-4b89-be02-06a2ec8b28c0.png)

**Comment by franciscovilchezv** [comment]
Gracias por las pruebas, pero no es necesario por si acaso.  Solo envíe el Pull Request para aprobarlo/realizar comentarios.
