### ISSUE TITLE
Errores ortográficos

### ISSUE THREAD

**Issue by EddisonPinedoEsp** [cs1000-utec/labs#23]
Adjunto relación de errores ortográficos y palabras incompletas que pude percibir en el laboratorio 9.
- Falta de tilde en la palabra "titulos" y coherencia. 
![Screenshot_173](https://user-images.githubusercontent.com/91136098/146294298-5c65675d-78af-4f13-9da0-2b5d3b5341a5.png)

> ###### "lista titulos" --> "lista de títulos"
- Falta la letra "i" en la palabra "utlizando".
![Screenshot_174](https://user-images.githubusercontent.com/91136098/146294761-97f8c122-271a-4186-8322-d8f820e0d14a.png)
> ###### "utlizando" --> "utilizando" 
- Falta de tilde en el pronombre "él".
![Screenshot_175](https://user-images.githubusercontent.com/91136098/146295208-dd039f20-285c-4967-a6bc-d5d56a6a99d9.png)
> ###### "para el" --> "para él"
- Falta la letra "c" en la palabra "ejericios".
![Screenshot_176](https://user-images.githubusercontent.com/91136098/146302933-f860f156-3208-443f-a1c9-9e756608063d.png)
> ##### "ejericios" --> "ejercicios"

**Comment by franciscovilchezv** [comment]
Ok
