### ISSUE TITLE
Implementación de todas las misiones 

### ISSUE THREAD

**Issue by Arnoldzevallos** [cs1000-utec/labs#25]
# PRESENTACIÓN DE LA PROBLEMÁTICA
Buen día, profesor Francisco. 
En esta oportunidad, accederé a cumplir con todas las misiones mencionadas en la tarea extra, es decir:
>- Corrección de ortografía
>- Detallar mejor algún punto en especifico.
>- Agregar solución a la parte práctica, en este caso del Lab11 - Ursina.
>- Implementar algunos ejercicios adicionales.
>- Videos tutoriales sobre la instalación de la librería `ursina`.

**A continuación, adjunto las imágenes en el cual me basaré:**

### Imágenes

>**Parte 1:** Corregiré algunos signos de puntuación, y agregaré los elementos de las áreas dividas del campo en una lista.

![](https://i.ibb.co/WvYKF9H/Imagen1.jpg)

-----------
>**Parte 2:** Corregiré ortografías y mostraré la entidad en mi compilador.

![](https://i.ibb.co/8jHst75/Imagen2.jpg)

-----------
>**Parte 3:** Implementaré los códigos en mi compilador; explicaré en un video, la función del código; añadiré una línea más de código, para que se note más entendible e interactivo.

![](https://i.ibb.co/GHLth7r/Imagen3.jpg)

-----------
>**Parte 4:** Mostraré un `resultado` diferente, pero usando las herramientas mencionadas en el comienzo.

![](https://i.ibb.co/s9v1KwT/Imagen4.jpg)

-----------
>**Parte 5:** Brindaré un ejercicio `especial`, incorporando nuestras dichas herramientas.

![](https://i.ibb.co/yQ79xPF/Imagen5.jpg)

-----------
#### FINALIDAD DE MI PRESENTACIÓN

![](https://i.ibb.co/h8pTTYY/Imagen6.png)

**Comment by franciscovilchezv** [comment]
- Parte 1: Proceder
- Parte 2: Proceder
- Parte 3 y 4: Si desea agregar otro ejemplo, incluirlo debajo del ejemplo ya existente. El video no es necesario, pero puede incluir si desea un gif en el que se vea cómo rota la cámara
- Parte 5: Puede incluirlo al final.
