### ISSUE TITLE
Error ortográfico- Lab 4

### ISSUE THREAD

**Issue by YaciraUTEC** [cs1000-utec/labs#26]
La palabra **"lenguages"** no existe en la RAE, quizás quiso decir _lenguajes._

![Captura de pantalla 2021-12-17 173504](https://user-images.githubusercontent.com/91109697/146616664-ec03bc1d-9d87-4ec9-a2d7-aa1b562d5417.png)

**Comment by franciscovilchezv** [comment]
Proceder
