### ISSUE TITLE
Dibujo de las iniciales de mi nombre con Ursina

### ISSUE THREAD

**Issue by RodrigoSebasT** [cs1000-utec/labs#28]
Usando el motor gráfico de python Ursina, he dibujado mis iniciales para recuperar el lab 11. Le dejo mi solución con todo lo pedido en el lab.

Nombre Rodrigo Sebastian Trujillo MIrano.
Curso: ICC laboratorio 1.02.
Horario: Jueves de 9:00 a 11:00 am.

[lab11.zip](https://github.com/cs1000-utec/labs/files/7738505/lab11.zip)

**Comment by franciscovilchezv** [comment]
Inválido. Seguir las indicaciones dadas en clase
