### ISSUE TITLE
Los errores ortográficos detectados en los laboratorios. 

### ISSUE THREAD

**Issue by anamariaaccilio** [cs1000-utec/labs#29]
Buenas tardes estimado profesor, estos son los errores ortográficos que pude observar a lo largo de los laboratorios. 

- **En el repositorio del laboratorio 4.**

1.  La palabra "lenguages" es incorrecta, se debería escribir `lenguajes`.
2.  La palabra "siguiento" es incorrecta, se debería escribir `siguiendo`.
![Lab 4, ortografía](https://user-images.githubusercontent.com/91237434/146629054-b22ee93d-ee1b-437d-b848-b5bf8d492e73.png)

- **En el repositorio del laboratorio 7 .**
1. La palabra "utilzando" no se encuentra identificada, se debería escribir `utilizando`.
2. La palabra "podra" es incorrecta, el término correcto es `podrá`, el cual significa  `Tener la facilidad de elaborar algo`.
![Lab7, ortografía](https://user-images.githubusercontent.com/91237434/146629296-26b12c7f-78d5-4032-aa4a-aa4f383d09db.png)

- **En el repositorio del laboratorio 8 .**
1. Falta una `coma` entre las palabras `que` y `en`, su manera correcta es **Esto quiere decir que`,` en lugar de guardar los datos.**
![Lab8, corrección (coma)](https://user-images.githubusercontent.com/91237434/146629391-27cf6349-c624-4fd8-bc14-d136b03a46e3.png)
2. La palabra "cuales" es incorrecta, se debería escribir `cuáles`, puesto que se denota una interrogación.
3. La palabra "indicale" es incorrecta, su forma de escribir correctamente es `indícale`.
![Lab 8, correción](https://user-images.githubusercontent.com/91237434/146629539-6812bba0-0ecf-4b1d-bdb2-0c2000d43d93.png)
- **En el repositorio del laboratorio 9 .**
1. El punto aparte (..) usado en este archivo es incorrecto, la forma idónea es `.`
![Lab 9, correción](https://user-images.githubusercontent.com/91237434/146629657-6de1081b-4c12-4581-9eb0-1cf7c8a19221.png)
2. La palabra "titulos" es incorrecta, se debería escribir `títulos`, con tilde. 
![Lab9, tilde](https://user-images.githubusercontent.com/91237434/146629695-f303abb1-2750-4bc6-a138-3b06cd81384f.png)
3.  La palabra "el" es la forma singular del pronombre personal masculino, por lo tanto debería ir con tilde, su manera correcta es `él`.
4. La palabra "ejericios" es incorrecta, se debería escribir `ejercicios`.
5. La palabra "solucion" es incorrecta, se debería escribir `solución`.
6. La palabra "funcion" es incorrecta, se debería escribir `función`.
![Lab 9, ortografía](https://user-images.githubusercontent.com/91237434/146629913-f2575352-498a-4663-8017-0a42a59289c5.png)

**MOTIVO: Punto para la PC1.**

**Comment by franciscovilchezv** [comment]
Proceder
