### ISSUE TITLE
Errores ortográficos detectados en el lab9

### ISSUE THREAD

**Issue by Mariana-Capunay** [cs1000-utec/labs#32]
Procederé a cambiar lo siguiente:

![falta_punto](https://user-images.githubusercontent.com/91635108/146655127-bfcb0b57-5aa1-474b-95be-a02696cb7e97.png)
Hace falta un punto en la parte señalada de amarillo.

-----------------------------------------------------------------------------------------------------------------------------------------------
![tilde_de_mas](https://user-images.githubusercontent.com/91635108/146655131-cdc13358-0853-4438-8dbf-2ea0ad4b7124.png)
![tilde](https://user-images.githubusercontent.com/91635108/146655162-3e1fc240-fd32-4a10-bcab-00d8d515d17d.png)
Hay una tilde de más en cada parte señalada de amarillo.

Motivo: Punto para la PC1
Nombre: Mariana Capuñay
Horario: Miércoles 3-5pm

**Comment by franciscovilchezv** [comment]
Proceder
