### ISSUE TITLE
#Errores ortográficos detectados en el lab 13 

### ISSUE THREAD

**Issue by LeoIsidro** [cs1000-utec/labs#37]
Procederé a realizar los siguientes cambios:
<img width="827" alt="f1" src="https://user-images.githubusercontent.com/90939274/146658601-40e8eec4-1a63-496c-a54e-0010a258dd7c.png">
- En la primera parte resaltada de amarillo hace falta una coma. 
- La segunda parte resaltada de amarillo no es comprensible, se comprenderia mejor si fuera : "que muchos de los siguientes 
  sectores estan utilizando tecnologia CV:".
****
<img width="803" alt="f2" src="https://user-images.githubusercontent.com/90939274/146658812-17984b89-5129-4095-bc28-3e836ca0f39e.png">

- En las partes resaltadas de amarillo hacen falta puntos.
**Motivo: Punto para PC1**

**Comment by franciscovilchezv** [comment]
Proceder
