### ISSUE TITLE
Errores ortográficos en el Lab10

### ISSUE THREAD

**Issue by MarielUTEC** [cs1000-utec/labs#38]
Quisiera realizar estos cambios en el Lab10:
![parte_1](https://user-images.githubusercontent.com/91162593/146659217-910d438e-9fb1-42fd-bf99-3923bdd491a0.png)
![parte_2](https://user-images.githubusercontent.com/91162593/146659238-56d8bfda-a234-4f92-95f4-a0269fdd7498.png)
### Parte 1: Falta un punto en las partes señaladas anteriormente

![parte_3](https://user-images.githubusercontent.com/91162593/146659261-d1cae507-e34d-48f3-a67b-ec2007c0369d.png)
### Motivo: Punto para la PC1

**Comment by franciscovilchezv** [comment]
Proceder
