### ISSUE TITLE
Error de puntuación en el lab8

### ISSUE THREAD

**Issue by NoemiHuarino-utec** [cs1000-utec/labs#41]
Realizaré los siguientes cambios:

![Correción1](https://user-images.githubusercontent.com/91573449/146664444-6a945ede-804a-44a3-a89a-363e6d056734.JPG)

![Correción2](https://user-images.githubusercontent.com/91573449/146664456-71dbdfcc-50b0-4aa2-b25e-7c96e1b6731d.JPG)

![Correción3](https://user-images.githubusercontent.com/91573449/146664462-5780ef78-3668-46c7-bbdc-c75c0d52e0f3.JPG)

Se deben añadir puntos en las partes resaltadas.

**Comment by franciscovilchezv** [comment]
Proceder
