### ISSUE TITLE
Error ortográfico-Lab5

### ISSUE THREAD

**Issue by OmarUTEC** [cs1000-utec/labs#43]
Error ortográfico en la palabra **guardardas** quizás quiso decir guardadas

![error (2)_LI](https://user-images.githubusercontent.com/91240794/146689298-2c600e59-f6a7-4104-ba05-4e7eccf3ab12.jpg)

**Comment by franciscovilchezv** [comment]
Proceder

**Comment by OmarUTEC** [comment]
_cs1000-utec#43: corregido_
